# Generated by Django 5.2.6 on 2026-05-21 16:08

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_sellerprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(max_length=255, verbose_name="Mağaza Adı"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=store.models.store_logo_path
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to=store.models.store_banner_path
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Mağaza E-posta"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Mağaza Telefon"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adres Satırı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("suspended", "Askıya Alındı"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mağaza",
                "verbose_name_plural": "Mağazalar",
            },
        ),
        migrations.CreateModel(
            name="StoreUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_store_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yeni Mağaza Adı"
                    ),
                ),
                (
                    "new_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="store_changes/logos/"
                    ),
                ),
                (
                    "new_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="store_changes/banners/"
                    ),
                ),
                (
                    "new_contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Yeni E-posta"
                    ),
                ),
                (
                    "new_contact_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Yeni Telefon"
                    ),
                ),
                (
                    "new_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yeni Adres Satırı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("suspended", "Askıya Alındı"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="store.store",
                    ),
                ),
            ],
        ),
    ]
