# Generated by Django 5.2.6 on 2026-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Onay Bekliyor"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                    ("suspended", "Askıya Alındı"),
                    ("archived", "Arşivlendi"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="storeupdaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Onay Bekliyor"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                    ("suspended", "Askıya Alındı"),
                    ("archived", "Arşivlendi"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
