# Generated by Django 5.2.6 on 2026-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_status_alter_storeupdaterequest_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storeupdaterequest",
            options={
                "verbose_name": "Mağaza Güncelleme Talebi",
                "verbose_name_plural": "Mağaza Güncelleme Talepleri",
            },
        ),
        migrations.AddConstraint(
            model_name="storeupdaterequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("store",),
                name="unique_pending_store_update_request",
            ),
        ),
    ]
