# Generated by Django 5.2.6 on 2025-09-16 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
        migrations.AlterModelOptions(
            name="sellerprofile",
            options={
                "verbose_name": "Satıcı Profili",
                "verbose_name_plural": "Satıcı Profilleri",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir telefon numarası girin. Örn: +905xxxxxxxxx",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="company_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir telefon numarası girin. Örn: +905xxxxxxxxx",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="iban",
            field=models.CharField(
                max_length=34,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Geçerli bir IBAN girin.",
                        regex="^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$",
                    )
                ],
                verbose_name="IBAN",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Örnek: Ev, İş", max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Geçerli bir telefon numarası girin. Örn: +905xxxxxxxxx",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Adres Satırı 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adres Satırı 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("state", models.CharField(max_length=100, verbose_name="İlçe")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Posta Kodu"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan Adres"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adres",
                "verbose_name_plural": "Adresler",
                "ordering": ["-is_default", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "title"), name="unique_user_title"
                    )
                ],
            },
        ),
    ]
