# Generated by Django 5.2.6 on 2026-06-15 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_sellerprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfileUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yeni Şirket Adı"
                    ),
                ),
                (
                    "new_company_address",
                    models.TextField(blank=True, verbose_name="Yeni Şirket Adresi"),
                ),
                (
                    "new_company_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Geçerli bir telefon numarası girin. Örn: +905xxxxxxxxx",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Yeni Telefon",
                    ),
                ),
                (
                    "new_iban",
                    models.CharField(
                        blank=True,
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Geçerli bir IBAN girin.",
                                regex="^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$",
                            )
                        ],
                        verbose_name="Yeni IBAN",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satıcı Bilgisi Değişiklik İsteği",
                "verbose_name_plural": "Satıcı Değişiklik İstekleri",
            },
        ),
    ]
