# Generated by Django 5.2.6 on 2026-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sellerprofileupdaterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="identity_number",
            field=models.CharField(
                blank=True,
                help_text="Bireysel satıcılar için T.C. kimlik numarası.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_last_error_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_last_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_onboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_onboarding_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Başlatılmadı"),
                    ("pending", "Bekliyor"),
                    ("active", "Aktif"),
                    ("failed", "Başarısız"),
                    ("suspended", "Askıya Alındı"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_submerchant_external_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_submerchant_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="legal_company_title",
            field=models.CharField(
                blank=True, help_text="Şirketin resmi ticari unvanı.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="seller_type",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "Bireysel"),
                    ("PRIVATE_COMPANY", "Şahıs Şirketi"),
                    ("LIMITED_OR_JOINT_STOCK_COMPANY", "Limited / Anonim Şirket"),
                ],
                default="PERSONAL",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="tax_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="tax_office",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
