# Generated by Django 5.2.6 on 2026-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sellerprofile_identity_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="iyzico_submerchant_external_id",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
