# Generated by Django 5.2.6 on 2026-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_sellerprofile_iyzico_submerchant_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="iyzico_onboarding_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="identity_number",
            field=models.CharField(
                blank=True,
                help_text="Bireysel ve şahıs şirketi satıcıları için T.C. kimlik numarası.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="iyzico_onboarding_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Başlatılmadı"),
                    ("pending", "Bekliyor"),
                    ("active", "Aktif"),
                    ("failed", "Başarısız"),
                    ("reconciliation_required", "Mutabakat Gerekli"),
                    ("suspended", "Askıya Alındı"),
                ],
                default="not_started",
                max_length=30,
            ),
        ),
    ]
