# Generated by Django 5.2.6 on 2026-09-27 11:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_sellerprofile_iyzico_onboarding_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="iban",
            field=models.CharField(
                max_length=34,
                validators=[accounts.models.validate_iban],
                verbose_name="IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofileupdaterequest",
            name="new_iban",
            field=models.CharField(
                blank=True,
                max_length=34,
                validators=[accounts.models.validate_iban],
                verbose_name="Yeni IBAN",
            ),
        ),
    ]
