# Generated by Django 5.2.6 on 2026-09-18 16:43

import django.core.validators
import django.db.models.deletion
import orders.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0022_productanswer_answer_per_question"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=orders.models.generate_order_number,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Sipariş Numarası",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Müşteri E-posta",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Müşteri Telefonu",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ara Toplam",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Kargo Tutarı",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Vergi Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Genel Toplam",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Ödeme Bekliyor"),
                            ("paid", "Ödendi"),
                            ("preparing", "Hazırlanıyor"),
                            ("partially_shipped", "Kısmen Kargolandı"),
                            ("shipped", "Kargolandı"),
                            ("delivered", "Teslim Edildi"),
                            ("cancelled", "İptal Edildi"),
                            ("expired", "Süresi Doldu"),
                            ("completed", "Tamamlandı"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=30,
                        verbose_name="Sipariş Durumu",
                    ),
                ),
                (
                    "shipping_full_name",
                    models.CharField(max_length=255, verbose_name="Teslimat Alıcısı"),
                ),
                (
                    "shipping_phone",
                    models.CharField(max_length=20, verbose_name="Teslimat Telefonu"),
                ),
                (
                    "shipping_address_line1",
                    models.CharField(max_length=255, verbose_name="Teslimat Adresi"),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Teslimat Adresi 2",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="Teslimat Şehri"),
                ),
                (
                    "shipping_state",
                    models.CharField(max_length=100, verbose_name="Teslimat İlçesi"),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(max_length=20, verbose_name="Teslimat Posta Kodu"),
                ),
                (
                    "billing_full_name",
                    models.CharField(max_length=255, verbose_name="Fatura Adı"),
                ),
                (
                    "billing_phone",
                    models.CharField(max_length=20, verbose_name="Fatura Telefonu"),
                ),
                (
                    "billing_address_line1",
                    models.CharField(max_length=255, verbose_name="Fatura Adresi"),
                ),
                (
                    "billing_address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Fatura Adresi 2",
                    ),
                ),
                (
                    "billing_city",
                    models.CharField(max_length=100, verbose_name="Fatura Şehri"),
                ),
                (
                    "billing_state",
                    models.CharField(max_length=100, verbose_name="Fatura İlçesi"),
                ),
                (
                    "billing_postal_code",
                    models.CharField(max_length=20, verbose_name="Fatura Posta Kodu"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ödeme Tarihi"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İptal Tarihi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş",
                "verbose_name_plural": "Siparişler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name_snapshot",
                    models.CharField(max_length=255, verbose_name="Ürün Adı"),
                ),
                (
                    "variant_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sipariş anındaki varyant özelliklerinin snapshot'ı. Örn: {'Renk': 'Siyah', 'Beden': 'XL'}",
                        verbose_name="Varyant Bilgisi",
                    ),
                ),
                (
                    "variant_display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UI için hazırlanmış varyant metni. Örn: Renk: Siyah, Beden: XL",
                        max_length=500,
                        verbose_name="Varyant Görünümü",
                    ),
                ),
                (
                    "sku_snapshot",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="SKU"
                    ),
                ),
                (
                    "barcode_snapshot",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Barkod"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Adet",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Birim Fiyat",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İndirim",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Vergi",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Satır Toplamı",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.storeproduct",
                        verbose_name="Mağaza Ürünü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Kalemi",
                "verbose_name_plural": "Sipariş Kalemleri",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        default="iyzico",
                        max_length=50,
                        verbose_name="Ödeme Sağlayıcı",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Provider Payment ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(max_length=100, verbose_name="Conversation ID"),
                ),
                (
                    "basket_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Basket ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Başlatıldı"),
                            ("pending", "Bekliyor"),
                            ("success", "Başarılı"),
                            ("failed", "Başarısız"),
                            ("refunded", "İade Edildi"),
                            ("partially_refunded", "Kısmen İade Edildi"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=30,
                        verbose_name="Ödeme Durumu",
                    ),
                ),
                (
                    "fraud_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Fraud Status"
                    ),
                ),
                (
                    "paid_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "last_four_digits",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Kart Son 4 Hane",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Kart Tipi"
                    ),
                ),
                (
                    "card_association",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Kart Markası",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "succeeded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başarılı Olma Tarihi"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                        verbose_name="Sipariş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme İşlemi",
                "verbose_name_plural": "Ödeme İşlemleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Provider Refund ID",
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        default=orders.models.generate_refund_reference,
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Refund Referansı",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="İade Tutarı",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("success", "Başarılı"),
                            ("failed", "Başarısız"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="İade Durumu",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="İade Nedeni",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Tamamlanma Tarihi"
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="orders.paymenttransaction",
                        verbose_name="Ödeme İşlemi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme İadesi",
                "verbose_name_plural": "Ödeme İadeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Rezerve Adet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif (Kilitli)"),
                            ("consumed", "Tüketildi (Satın Alındı)"),
                            ("released", "Serbest Bırakıldı (İptal)"),
                            ("expired", "Süresi Doldu"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Rezervasyon Durumu",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Rezervasyon Bitiş Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="orders.orderitem",
                        verbose_name="Sipariş Kalemi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Rezervasyonu",
                "verbose_name_plural": "Stok Rezervasyonları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suborder_number",
                    models.CharField(
                        default=orders.models.generate_suborder_number,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Alt Sipariş Numarası",
                    ),
                ),
                (
                    "store_name_snapshot",
                    models.CharField(
                        max_length=255, verbose_name="Sipariş Anındaki Mağaza Adı"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ara Toplam",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Kargo Tutarı",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Vergi Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Genel Toplam",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("preparing", "Hazırlanıyor"),
                            ("shipped", "Kargolandı"),
                            ("delivered", "Teslim Edildi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Mağaza Sipariş Durumu",
                    ),
                ),
                (
                    "cargo_company",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Kargo Firması",
                    ),
                ),
                (
                    "cargo_tracking_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="Kargo Takip Numarası",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kargoya Verilme Tarihi"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Teslim Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_orders",
                        to="orders.order",
                        verbose_name="Ana Sipariş",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_orders",
                        to="store.store",
                        verbose_name="Mağaza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mağaza Siparişi",
                "verbose_name_plural": "Mağaza Siparişleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sub_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.suborder",
                verbose_name="Mağaza Siparişi",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="order_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="order_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="order_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="order_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="order_shipping_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="order_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)), name="order_total_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["order", "-created_at"], name="payment_order_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["status", "-created_at"], name="payment_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_id__isnull", False)),
                fields=("provider", "payment_id"),
                name="unique_provider_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                fields=("provider", "conversation_id"),
                name="unique_provider_conversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_price__gte", 0),
                    ("paid_price__isnull", True),
                    _connector="OR",
                ),
                name="payment_paid_price_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["payment_transaction", "-created_at"],
                name="refund_payment_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["status", "-created_at"], name="refund_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_refund_id__isnull", False)),
                fields=("payment_transaction", "provider_refund_id"),
                name="unique_provider_refund",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_gt_0"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["order_item", "status"], name="reservation_item_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="reservation_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("order_item",),
                name="unique_active_reservation_per_item",
            ),
        ),
        migrations.AddIndex(
            model_name="suborder",
            index=models.Index(
                fields=["store", "-created_at"], name="suborder_store_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suborder",
            index=models.Index(
                fields=["status", "-created_at"], name="suborder_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.UniqueConstraint(
                fields=("order", "store"), name="unique_store_per_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="suborder_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="suborder_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="suborder_shipping_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="suborder_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="suborder_total_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["sub_order", "id"], name="orderitem_suborder_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="orderitem_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="orderitem_unit_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="orderitem_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="orderitem_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="orderitem_total_gte_0",
            ),
        ),
    ]
