# Generated by Django 5.2.6 on 2026-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_identity_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
