# Generated by Django 5.2.6 on 2026-09-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_buyer_identity_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        default="iyzico",
                        max_length=50,
                        verbose_name="Ödeme Sağlayıcı",
                    ),
                ),
                (
                    "provider_customer_key",
                    models.CharField(
                        max_length=255, verbose_name="Provider Customer Key"
                    ),
                ),
                (
                    "provider_external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Provider External ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Müşterisi",
                "verbose_name_plural": "Ödeme Müşterileri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_card_token",
                    models.CharField(
                        max_length=255, verbose_name="Provider Card Token"
                    ),
                ),
                (
                    "card_alias",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=293,
                        verbose_name="Kart Takma Adı",
                    ),
                ),
                (
                    "bin_number",
                    models.CharField(
                        blank=True, default="", max_length=8, verbose_name="BIN"
                    ),
                ),
                (
                    "last_four_digits",
                    models.CharField(max_length=4, verbose_name="Son 4 Hane"),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Kart Tipi"
                    ),
                ),
                (
                    "card_association",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Kart Markası",
                    ),
                ),
                (
                    "card_family",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Kart Ailesi",
                    ),
                ),
                (
                    "card_bank_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Banka Kodu"
                    ),
                ),
                (
                    "card_bank_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Banka Adı"
                    ),
                ),
                (
                    "expire_month",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        verbose_name="Son Kullanma Ayı",
                    ),
                ),
                (
                    "expire_year",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=4,
                        verbose_name="Son Kullanma Yılı",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan Kart"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Aktif"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "payment_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_cards",
                        to="orders.paymentcustomer",
                        verbose_name="Ödeme Müşterisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıtlı Kart",
                "verbose_name_plural": "Kayıtlı Kartlar",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentcustomer",
            index=models.Index(
                fields=["user", "provider"], name="paycust_user_prov_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcustomer",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="unique_payment_customer_provider"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcustomer",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_customer_key"),
                name="unique_provider_customer_key",
            ),
        ),
        migrations.AddIndex(
            model_name="storedcard",
            index=models.Index(
                fields=["payment_customer", "is_active"], name="stcard_cust_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedcard",
            index=models.Index(
                fields=["payment_customer", "is_default"],
                name="stcard_cust_default_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcard",
            constraint=models.UniqueConstraint(
                fields=("payment_customer", "provider_card_token"),
                name="unique_stored_card_token",
            ),
        ),
    ]
