# Generated by Django 5.2.6 on 2026-09-30 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_paymentcustomer_storedcard_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredCardOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="iyzico", max_length=30)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("CREATE", "Create"), ("DELETE", "Delete")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROVIDER_SUCCEEDED", "Provider Succeeded"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RECONCILIATION_REQUIRED", "Reconciliation Required"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("make_default", models.BooleanField(default=False)),
                (
                    "provider_card_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provider_customer_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "provider_external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="storedcard",
            options={
                "ordering": ["-is_default", "-created_at", "-pk"],
                "verbose_name": "Kayıtlı Kart",
                "verbose_name_plural": "Kayıtlı Kartlar",
            },
        ),
        migrations.RemoveConstraint(
            model_name="storedcard",
            name="unique_stored_card_token",
        ),
        migrations.AddConstraint(
            model_name="storedcard",
            constraint=models.UniqueConstraint(
                fields=("payment_customer", "provider_card_token"),
                name="unique_stcard_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("payment_customer",),
                name="unique_act_def_stcard",
            ),
        ),
        migrations.AddField(
            model_name="storedcardoperation",
            name="stored_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="orders.storedcard",
            ),
        ),
        migrations.AddField(
            model_name="storedcardoperation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_card_operations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="storedcardoperation",
            index=models.Index(
                fields=["user", "operation_type", "status", "created_at"],
                name="op_user_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storedcardoperation",
            index=models.Index(
                fields=["stored_card", "operation_type", "status"],
                name="op_card_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcardoperation",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "operation_type", "idempotency_key"),
                name="stcard_idmptncy_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcardoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("operation_type", "CREATE"),
                    (
                        "status__in",
                        ["PENDING", "PROVIDER_SUCCEEDED", "RECONCILIATION_REQUIRED"],
                    ),
                ),
                fields=("user", "provider", "operation_type"),
                name="active_stcard_create",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcardoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("operation_type", "DELETE"),
                    (
                        "status__in",
                        ["PENDING", "PROVIDER_SUCCEEDED", "RECONCILIATION_REQUIRED"],
                    ),
                ),
                fields=("stored_card", "provider", "operation_type"),
                name="active_stcard_delete",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedcardoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("operation_type", "CREATE"), ("stored_card__isnull", True)
                    ),
                    models.Q(
                        ("operation_type", "DELETE"), ("stored_card__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="stcard_target_valid",
            ),
        ),
    ]
