# Generated by Django 5.2.6 on 2026-09-30 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_storedcardoperation_alter_storedcard_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storedcardoperation",
            name="stcard_target_valid",
        ),
        migrations.AddConstraint(
            model_name="storedcardoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operation_type", "CREATE"),
                    models.Q(
                        ("operation_type", "DELETE"), ("stored_card__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="stcard_target_valid",
            ),
        ),
    ]
