# Generated by Django 5.2.6 on 2026-10-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("orders", "0005_remove_storedcardoperation_stcard_target_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="source_cart_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cart.cartitem",
                verbose_name="Kaynak Sepet Ürünü",
            ),
        ),
    ]
