# Generated by Django 5.2.6 on 2026-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_source_cart_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="source_cart_item_updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Checkout Anındaki Sepet Ürünü Güncellenme Tarihi",
            ),
        ),
    ]
