# Generated by Django 5.2.6 on 2026-10-02 15:27

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderitem_source_cart_item_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image_snapshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=orders.models.order_item_image_snapshot_upload_to,
                verbose_name="Ürün Görseli Snapshot",
            ),
        ),
    ]
