# Generated by Django 5.2.6 on 2026-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderitem_image_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="İndirim Kodu Snapshot",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="installment_count",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Taksit Sayısı"
            ),
        ),
    ]
