# Generated by Django 5.2.6 on 2026-10-03 20:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_discount_code_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Fatura Numarası",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Düzenlenme Tarihi"
                    ),
                ),
                (
                    "seller_display_name",
                    models.CharField(max_length=255, verbose_name="Satıcı Görünen Adı"),
                ),
                (
                    "seller_legal_company_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Satıcı Yasal Unvanı"
                    ),
                ),
                ("seller_address", models.TextField(verbose_name="Satıcı Adresi")),
                (
                    "seller_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Satıcı Telefonu"
                    ),
                ),
                (
                    "seller_tax_office",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "seller_tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Vergi Numarası"
                    ),
                ),
                (
                    "seller_identity_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Satıcı T.C. Kimlik Numarası",
                    ),
                ),
                (
                    "buyer_full_name",
                    models.CharField(max_length=255, verbose_name="Alıcı Adı Soyadı"),
                ),
                (
                    "buyer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Alıcı Telefonu"
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Alıcı E-posta"
                    ),
                ),
                (
                    "buyer_identity_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Alıcı T.C. Kimlik / Vergi Numarası",
                    ),
                ),
                (
                    "buyer_billing_address_line1",
                    models.CharField(max_length=255, verbose_name="Fatura Adresi"),
                ),
                (
                    "buyer_billing_address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Fatura Adresi 2"
                    ),
                ),
                (
                    "buyer_billing_city",
                    models.CharField(max_length=100, verbose_name="Fatura Şehri"),
                ),
                (
                    "buyer_billing_state",
                    models.CharField(max_length=100, verbose_name="Fatura İlçesi"),
                ),
                (
                    "buyer_billing_postal_code",
                    models.CharField(max_length=20, verbose_name="Fatura Posta Kodu"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Ara Toplam"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Kargo Tutarı",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Vergi Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Genel Toplam"
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=3, verbose_name="Para Birimi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "suborder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="orders.suborder",
                        verbose_name="Alt Sipariş",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Ürün Adı"),
                ),
                (
                    "variant_display",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Varyant"
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=100, verbose_name="SKU"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="Barkod"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Miktar")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Vergi Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="orders.invoice",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="invoice_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="invoice_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="invoice_shipping_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="invoice_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)), name="invoice_total_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="invoice_item_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_item_unit_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="invoice_item_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)),
                name="invoice_item_tax_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="invoice_item_total_gte_0",
            ),
        ),
    ]
