# Generated by Django 5.2.6 on 2026-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_invoice_invoiceitem_invoice_invoice_subtotal_gte_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suborder",
            name="cargo_company",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yurtici", "Yurtiçi Kargo"),
                    ("aras", "Aras Kargo"),
                    ("surat", "Sürat Kargo"),
                    ("ptt", "PTT Kargo"),
                    ("ups", "UPS"),
                    ("dhl", "DHL"),
                    ("kolaygelsin", "Kolay Gelsin"),
                ],
                default="",
                max_length=30,
                verbose_name="Kargo Firması",
            ),
        ),
    ]
