# Generated by Django 5.2.6 on 2026-10-04 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_suborder_cargo_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrefund",
            name="suborder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_refunds",
                to="orders.suborder",
                verbose_name="Alt Sipariş",
            ),
        ),
        migrations.AddField(
            model_name="suborder",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="İptal Tarihi"
            ),
        ),
        migrations.CreateModel(
            name="SubOrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="İptal Nedeni"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İade Tutarı",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İptal Tarihi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suborder_cancellations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İptal Eden",
                    ),
                ),
                (
                    "payment_refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation",
                        to="orders.paymentrefund",
                        verbose_name="Ödeme İadesi",
                    ),
                ),
                (
                    "suborder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation",
                        to="orders.suborder",
                        verbose_name="Alt Sipariş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alt Sipariş İptali",
                "verbose_name_plural": "Alt Sipariş İptalleri",
                "ordering": ["-cancelled_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("refund_amount__gte", 0)),
                        name="suborder_cancel_refund_gte_0",
                    )
                ],
            },
        ),
    ]
