# Generated by Django 5.2.6 on 2026-10-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_paymentrefund_suborder_suborder_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrefund",
            name="suborder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_refunds",
                to="orders.suborder",
                verbose_name="Alt Sipariş",
            ),
        ),
    ]
