# Generated by Django 5.2.6 on 2026-10-05 12:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_paymentrefund_suborder"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="İade Tutarı",
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Provider Refund ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("success", "Başarılı"),
                            ("failed", "Başarısız"),
                            ("reconciliation_required", "Mutabakat Gerekiyor"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="İade Durumu",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Refund Conversation ID",
                    ),
                ),
                (
                    "retryable",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Tekrar Denenebilir"
                    ),
                ),
                (
                    "provider_error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "provider_error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ödeme İade Kalemi",
                "verbose_name_plural": "Ödeme İade Kalemleri",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("product", "Ürün"), ("shipping", "Kargo")],
                        max_length=20,
                    ),
                ),
                (
                    "provider_item_id",
                    models.CharField(max_length=100, verbose_name="Provider Item ID"),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        max_length=100, verbose_name="Provider Payment Transaction ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Provider Kalem Tutarı",
                    ),
                ),
                (
                    "paid_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tahsil Edilen Kalem Tutarı",
                    ),
                ),
                (
                    "transaction_status",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Provider Transaction Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ödeme İşlem Kalemi",
                "verbose_name_plural": "Ödeme İşlem Kalemleri",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="paymentrefund",
                    name="unique_provider_refund",
                ),
                migrations.RemoveField(
                    model_name="paymentrefund",
                    name="provider_refund_id",
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="refund_shipping",
            field=models.BooleanField(
                default=False, verbose_name="Kargo Ücreti İade Ediliyor"
            ),
        ),
        migrations.AddField(
            model_name="paymentrefund",
            name="refund_type",
            field=models.CharField(
                choices=[
                    ("suborder_cancellation", "Alt Sipariş İptali"),
                    ("customer_request", "Müşteri Talebi"),
                    ("seller_fault", "Satıcı Kaynaklı"),
                ],
                default="suborder_cancellation",
                max_length=30,
                verbose_name="İade Türü",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentrefund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("processing", "İşleniyor"),
                    ("success", "Başarılı"),
                    ("failed", "Başarısız"),
                    ("reconciliation_required", "Mutabakat Gerekiyor"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="İade Durumu",
            ),
        ),
        migrations.AddField(
            model_name="paymentrefunditem",
            name="payment_refund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="orders.paymentrefund",
                verbose_name="Ödeme İadesi",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransactionitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transaction_items",
                to="orders.orderitem",
                verbose_name="Sipariş Kalemi",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransactionitem",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="orders.paymenttransaction",
                verbose_name="Ödeme İşlemi",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransactionitem",
            name="suborder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transaction_items",
                to="orders.suborder",
            ),
        ),
        migrations.AddField(
            model_name="paymentrefunditem",
            name="payment_transaction_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_items",
                to="orders.paymenttransactionitem",
                verbose_name="Ödeme İşlem Kalemi",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransactionitem",
            index=models.Index(
                fields=["payment_transaction", "suborder"], name="ptxitem_pay_sub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransactionitem",
            index=models.Index(
                fields=["payment_transaction", "order_item"], name="ptxitem_pay_ord_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.UniqueConstraint(
                fields=("payment_transaction", "provider_item_id"),
                name="unique_payment_provider_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.UniqueConstraint(
                fields=("payment_transaction", "provider_transaction_id"),
                name="unique_payment_provider_tx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.UniqueConstraint(
                fields=("provider_transaction_id",),
                name="unique_provider_transaction_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_item__isnull", False)),
                fields=("payment_transaction", "order_item"),
                name="unique_payment_order_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_type", "shipping")),
                fields=("payment_transaction", "suborder"),
                name="unique_payment_shipping_suborder",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransactionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "product"), ("order_item__isnull", False)),
                    models.Q(("item_type", "shipping"), ("order_item__isnull", True)),
                    _connector="OR",
                ),
                name="payment_item_type_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefunditem",
            index=models.Index(
                fields=["status", "-created_at"], name="refunditem_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefunditem",
            index=models.Index(
                fields=["payment_transaction_item", "status"], name="ptxitem_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefunditem",
            constraint=models.UniqueConstraint(
                fields=("payment_refund", "payment_transaction_item"),
                name="unique_refund_transaction_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefunditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_refund_id__isnull", False)),
                fields=("provider_refund_id",),
                name="unique_refund_item_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrefunditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_item_amount_gt_0"
            ),
        ),
    ]
