# Generated by Django 5.2.6 on 2026-10-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_paymentrefunditem_paymenttransactionitem_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentrefunditem",
            name="unique_refund_item_provider_id",
        ),
    ]
