# Generated by Django 5.2.6 on 2026-07-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0002_alter_store_status_alter_storeupdaterequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Özellik Adı (Örn: Renk, Beden)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Marka Adı"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Marka",
                "verbose_name_plural": "Markalar",
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=100, verbose_name="Değer (Örn: Kırmızı, XL, 128GB)"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özellik Değeri",
                "verbose_name_plural": "Özellik Değerleri",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Kategori Adı")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                        verbose_name="Üst Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=True, verbose_name="Filtreleme yapılabilir mi?"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Zorunlu mu?"),
                ),
                (
                    "is_variant",
                    models.BooleanField(
                        default=True, verbose_name="Varyant oluşturuyor mu?"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="products.attribute",
                        verbose_name="Özellik",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_attributes",
                        to="products.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori Özelliği",
                "verbose_name_plural": "Kategori Özellikleri",
                "ordering": ["sort_order", "attribute__name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ürün Adı")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(verbose_name="Genel Ürün Açıklaması")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Sistemde Aktif mi?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Ürün",
                "verbose_name_plural": "Global Ürünler",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Barkod (EAN/UPC)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Varyant Aktif mi?"),
                ),
                (
                    "attribute_values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="variants",
                        to="products.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Varyantı",
                "verbose_name_plural": "Ürün Varyantları",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/images/")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Kapak Fotoğrafı mı?"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_images",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Görseli",
                "verbose_name_plural": "Ürün Görselleri",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Satıcı Stok Kodu (SKU)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Stok Adedi"),
                ),
                (
                    "sold_count",
                    models.PositiveIntegerField(default=0, verbose_name="Satış Sayısı"),
                ),
                (
                    "seller_notes",
                    models.TextField(blank=True, verbose_name="Satıcıya Özel Notlar"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Yayında"),
                            ("draft", "Taslak"),
                            ("out_of_stock", "Tükendi"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="store.store",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_offers",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satıcı Teklifi (Envanter)",
                "verbose_name_plural": "Satıcı Teklifleri",
            },
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Değişen Fiyat"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Değişim Tarihi"
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiyat Geçmişi",
                "verbose_name_plural": "Fiyat Geçmişleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "value"), name="unique_attribute_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryattribute",
            constraint=models.UniqueConstraint(
                fields=("category", "attribute"), name="unique_category_attribute"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["variant", "status", "price"],
                name="products_st_variant_4d221b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["store", "status"], name="products_st_store_i_334aed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeproduct",
            constraint=models.UniqueConstraint(
                fields=("store", "variant"), name="unique_store_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku__isnull", False)),
                fields=("store", "sku"),
                name="unique_store_sku",
            ),
        ),
    ]
