# Generated by Django 5.2.6 on 2026-07-08 20:18

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Ürün Görseli",
                "verbose_name_plural": "Ürün Görselleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["id"],
                "verbose_name": "Ürün Varyantı",
                "verbose_name_plural": "Ürün Varyantları",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.AddField(
            model_name="attribute",
            name="is_visual",
            field=models.BooleanField(
                default=False,
                help_text="Örn: Renk, Ekran Boyutu, Kasa Tipi.",
                verbose_name="Görselleri Değiştirir mi?",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_product",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Taslak"),
                    ("active", "Yayında"),
                    ("archived", "Arşivlendi"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=products.models.product_image_upload_to),
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="variant",
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="unique_main_image_per_product",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ManyToManyField(
                blank=True,
                related_name="variant_images",
                to="products.productvariant",
                verbose_name="Bağlı Varyantlar",
            ),
        ),
    ]
