# Generated by Django 5.2.6 on 2026-07-10 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_brandrequest_categorybrand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="brandrequest",
            constraint=models.UniqueConstraint(
                fields=("seller", "category", "brand_name"),
                name="unique_brand_request_per_seller",
            ),
        ),
    ]
