# Generated by Django 5.2.6 on 2026-07-15 18:29

import django.core.validators
import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brandrequest_unique_brand_request_per_seller"),
        ("store", "0002_alter_store_status_alter_storeupdaterequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="allow_custom_values",
            field=models.BooleanField(
                default=False, verbose_name="Satıcı yeni değer ekleyebilir mi?"
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="brandrequest",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="normalized_key",
            field=models.CharField(
                db_index=True, default=1, editable=False, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="tokens",
            field=models.JSONField(
                default=list, editable=False, verbose_name="Ürün Kelimeleri"
            ),
        ),
        migrations.CreateModel(
            name="ProductDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ürün Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                (
                    "normalized_key",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                (
                    "tokens",
                    models.JSONField(
                        default=list, editable=False, verbose_name="Ürün Kelimeleri"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("none", "Eşleşme Yok"),
                            ("pending", "Karar Bekleniyor"),
                            ("accepted", "Mevcut Ürün Kullanılacak"),
                            ("rejected", "Yeni Ürün Oluşturulacak"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                        verbose_name="Eşleşme Durumu",
                    ),
                ),
                ("last_completed_step", models.PositiveSmallIntegerField(default=1)),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Mevcut Adım",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("completed", "Tamamlandı"),
                            ("published", "Yayınlandı"),
                            ("canceled", "İptal Edildi"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarihi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_drafts",
                        to="products.brand",
                        verbose_name="Marka",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_drafts",
                        to="products.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_drafts",
                        to="products.product",
                    ),
                ),
                (
                    "published_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Satıcı",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_drafts",
                        to="store.store",
                        verbose_name="Mağaza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Taslağı",
                "verbose_name_plural": "Ürün Taslakları",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductDraftVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Barkod"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="draft_variants",
                        to="products.attributevalue",
                        verbose_name="Özellikler",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.productdraft",
                        verbose_name="Taslak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taslak Varyant",
                "verbose_name_plural": "Taslak Varyantlar",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductDraftImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.draft_image_upload_to,
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt Metin"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Kapak Görseli mi?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productdraft",
                        verbose_name="Taslak",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boş ise ana ürün görselidir.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productdraftvariant",
                        verbose_name="Varyant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taslak Görsel",
                "verbose_name_plural": "Taslak Görselleri",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["seller", "status"], name="products_pr_seller__2f084b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["seller", "match_status"], name="products_pr_seller__fd60d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["store", "status"], name="products_pr_store_i_142a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["category", "brand"], name="products_pr_categor_c7900b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["normalized_name", "brand", "category"],
                name="products_pr_normali_26bf95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productdraft",
            index=models.Index(
                fields=["seller", "updated_at"], name="products_pr_seller__29d001_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_step__gte", 1), ("current_step__lte", 4)),
                name="valid_product_draft_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("seller", "store", "category", "normalized_key"),
                name="unique_active_product_draft",
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftvariant",
            index=models.Index(
                fields=["draft", "is_active"], name="products_pr_draft_i_47fc33_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftvariant",
            constraint=models.UniqueConstraint(
                fields=("draft", "sort_order"), name="unique_draft_variant_sort_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False)),
                fields=("draft", "barcode"),
                name="unique_draft_variant_barcode",
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimage",
            index=models.Index(
                fields=["draft", "sort_order"], name="products_pr_draft_i_b10404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimage",
            index=models.Index(
                fields=["variant"], name="products_pr_variant_9832df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimage",
            index=models.Index(
                fields=["draft", "is_active"], name="products_pr_draft_i_eaa11d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("draft",),
                name="unique_main_draft_image",
            ),
        ),
    ]
