# Generated by Django 5.2.6 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_attribute_allow_custom_values_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="allow_custom_values",
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="allow_custom_values",
            field=models.BooleanField(
                default=False, verbose_name="Satıcı yeni değer ekleyebilir mi?"
            ),
        ),
    ]
