# Generated by Django 5.2.6 on 2026-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_attribute_allow_custom_values_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="is_visual",
        ),
        migrations.AddField(
            model_name="categoryattribute",
            name="is_visual",
            field=models.BooleanField(
                default=False,
                help_text="Örn: Renk, Ekran Boyutu, Kasa Tipi.",
                verbose_name="Görselleri Değiştirir mi?",
            ),
        ),
    ]
