# Generated by Django 5.2.6 on 2026-07-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_attribute_is_visual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDraftImageGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taslak Görsel Grubu",
                "verbose_name_plural": "Taslak Görsel Grupları",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImageGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="productdraftimage",
            name="unique_main_draft_image",
        ),
        migrations.RemoveConstraint(
            model_name="productimage",
            name="unique_main_image_per_product",
        ),
        migrations.RemoveIndex(
            model_name="productdraftimage",
            name="products_pr_draft_i_b10404_idx",
        ),
        migrations.RemoveIndex(
            model_name="productdraftimage",
            name="products_pr_variant_9832df_idx",
        ),
        migrations.RemoveIndex(
            model_name="productdraftimage",
            name="products_pr_draft_i_eaa11d_idx",
        ),
        migrations.RemoveField(
            model_name="productdraftimage",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="productdraftimage",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="variant",
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alt Metin"
            ),
        ),
        migrations.AddField(
            model_name="productdraftimagegroup",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_groups",
                to="products.productdraft",
                verbose_name="Taslak",
            ),
        ),
        migrations.AddField(
            model_name="productdraftimagegroup",
            name="visual_attribute_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="Yalnızca is_visual=True olan özellik değerleri eklenmelidir. Boş bırakılırsa ortak görsel grubudur.",
                related_name="draft_image_groups",
                to="products.attributevalue",
                verbose_name="Görsel Özellikleri",
            ),
        ),
        migrations.AddField(
            model_name="productdraftimage",
            name="group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productdraftimagegroup",
                verbose_name="Görsel Grubu",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="productdraftimage",
            index=models.Index(
                fields=["group", "sort_order"], name="products_pr_group_i_112307_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimage",
            index=models.Index(
                fields=["group", "is_active"], name="products_pr_group_i_9ac9c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("group",),
                name="unique_main_draft_image_per_group",
            ),
        ),
        migrations.AddField(
            model_name="productimagegroup",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_groups",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productimagegroup",
            name="visual_attribute_values",
            field=models.ManyToManyField(
                blank=True,
                help_text="Yalnızca is_visual=True olan attribute değerleri eklenmelidir.",
                related_name="image_groups",
                to="products.attributevalue",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productimagegroup",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("group",),
                name="unique_main_product_image_per_group",
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimagegroup",
            index=models.Index(
                fields=["draft", "sort_order"], name="products_pr_draft_i_646e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftimagegroup",
            index=models.Index(
                fields=["draft", "is_active"], name="products_pr_draft_i_d1f7bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimagegroup",
            index=models.Index(
                fields=["product", "sort_order"], name="products_pr_product_4b2de9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimagegroup",
            index=models.Index(
                fields=["product", "is_active"], name="products_pr_product_7acf53_idx"
            ),
        ),
    ]
