# Generated by Django 5.2.6 on 2026-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productdraftimagegroup_productimagegroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdraftimage",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=32,
                null=True,
                verbose_name="Dosya Parmak İzi (MD5)",
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_hash__isnull", False)),
                fields=("group", "file_hash"),
                name="unique_image_hash_per_group",
            ),
        ),
    ]
