# Generated by Django 5.2.6 on 2026-08-02 08:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productdraftimage_file_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdraftvariant",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Varsayılan Varyant"),
        ),
        migrations.AddField(
            model_name="productdraftvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Satış Fiyatı"
            ),
        ),
        migrations.AddField(
            model_name="productdraftvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Satıcı Stok Kodu (SKU)",
            ),
        ),
        migrations.AddField(
            model_name="productdraftvariant",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stok"),
        ),
        migrations.AlterField(
            model_name="productdraftvariant",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Barkod",
            ),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Satış Fiyatı",
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftvariant",
            index=models.Index(
                fields=["draft", "is_default"], name="products_pr_draft_i_342a69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdraftvariant",
            index=models.Index(
                fields=["draft", "sort_order"], name="products_pr_draft_i_b31f16_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku__isnull", False)),
                fields=("draft", "sku"),
                name="unique_draft_variant_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="productdraftvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("draft",),
                name="unique_default_draft_variant",
            ),
        ),
    ]
