# Generated by Django 5.2.6 on 2026-08-03 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_productdraftvariant_is_default_and_more"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productdraft",
            name="valid_product_draft_step",
        ),
        migrations.AddConstraint(
            model_name="productdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_step__gte", 1), ("current_step__lte", 5)),
                name="valid_product_draft_step",
            ),
        ),
    ]
