# Generated by Django 5.2.6 on 2026-08-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_created_by"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
        migrations.AddField(
            model_name="product",
            name="created_by_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to="store.store",
                verbose_name="Oluşturan Mağaza",
            ),
        ),
    ]
