# Generated by Django 5.2.6 on 2026-08-28 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_remove_product_created_by_product_created_by_store"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Liste Adı")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Kullanıcı düz kalbe tıkladığında ürün bu listeye düşer.",
                        verbose_name="Varsayılan Favori Listesi mi?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Koleksiyonu",
                "verbose_name_plural": "Ürün Koleksiyonları",
                "ordering": ["-is_default", "-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProductCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.productcollection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koleksiyon Ürünü",
                "verbose_name_plural": "Koleksiyon Ürünleri",
                "ordering": ["-added_at"],
                "unique_together": {("collection", "product")},
            },
        ),
    ]
