# Generated by Django 5.2.6 on 2026-08-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_productcollection_productcollectionitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcollectionitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productcollectionitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="products.productvariant",
                verbose_name="Varyant",
            ),
        ),
        migrations.RemoveField(
            model_name="productcollectionitem",
            name="product",
        ),
    ]
