# Generated by Django 5.2.6 on 2026-08-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_productcollectionitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcollectionitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="products.productvariant",
                verbose_name="Varyant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcollectionitem",
            unique_together={("collection", "variant")},
        ),
    ]
