# Generated by Django 5.2.6 on 2026-08-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_productcollectionitem_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcollectionitem",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by",
                to="products.storeproduct",
                verbose_name="Eklenen Teklif",
            ),
        ),
    ]
