# Generated by Django 5.2.6 on 2026-08-30 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_productcollectionitem_offer"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "Genel"),
                            ("price", "Fiyat / İndirim"),
                            ("payment", "Ödeme"),
                            ("availability", "Stok / Bulunabilirlik"),
                            ("shipping", "Kargo / Teslimat"),
                            ("warranty", "Garanti / İade"),
                            ("gift", "Hediye Gönderimi"),
                            ("model_variant", "Model / Versiyon Farklılıkları"),
                            ("features", "Fonksiyon / Özellikler"),
                            ("content", "Ürün İçeriği"),
                            ("material", "Malzeme"),
                            ("color", "Renk Seçenekleri"),
                            ("size", "Boyut / Ölçü"),
                            ("weight", "Ağırlık"),
                            ("quantity", "Adet / Miktar"),
                            ("origin", "Menşei / Üretim Yeri"),
                            ("usage_area", "Kullanım Alanları"),
                            ("usage_instructions", "Kullanım Talimatları"),
                            ("installation", "Kurulum / Montaj"),
                            ("care", "Bakım / Temizlik"),
                            ("storage", "Saklama Koşulları"),
                            ("compatibility", "Uyumluluk"),
                            ("suitability", "Uygunluk"),
                            ("age", "Yaş Uygunluğu"),
                            ("safety", "Güvenlik"),
                            ("allergy", "Alerji / Hassasiyet"),
                            ("performance", "Performans"),
                            ("expiry", "Son Kullanma Tarihi"),
                            ("certification", "Sertifika / Standartlar"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Konu",
                    ),
                ),
                ("text", models.TextField(max_length=1000, verbose_name="Soru Metni")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Vitrinde Görünsün mü?"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="İsmimi Gizle"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="Cevaplandı mı?"),
                ),
                (
                    "upvotes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Faydalı Bulma Sayısı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="products.product",
                    ),
                ),
                (
                    "target_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_questions",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Sorusu",
                "verbose_name_plural": "Ürün Soruları",
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="Cevap Metni")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Vitrinde Görünsün mü?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_answers",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.productquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soru Cevabı",
                "verbose_name_plural": "Soru Cevapları",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "is_visible", "-upvotes"],
                name="question_product_visible",
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "target_store", "is_visible"],
                name="question_store_visible",
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "topic", "is_visible"], name="question_topic_visible"
            ),
        ),
        migrations.AddIndex(
            model_name="productanswer",
            index=models.Index(
                fields=["question", "is_visible", "created_at"],
                name="answer_question_visible",
            ),
        ),
        migrations.AddIndex(
            model_name="productanswer",
            index=models.Index(
                fields=["store", "is_visible"], name="answer_store_visible"
            ),
        ),
    ]
