# Generated by Django 5.2.6 on 2026-08-31 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_productquestion_productanswer_and_more"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestionUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Soru Faydalı Oyu",
                "verbose_name_plural": "Soru Faydalı Oyları",
            },
        ),
        migrations.AlterModelOptions(
            name="productquestion",
            options={
                "verbose_name": "Ürün Sorusu",
                "verbose_name_plural": "Ürün Soruları",
            },
        ),
        migrations.RemoveIndex(
            model_name="productanswer",
            name="answer_store_visible",
        ),
        migrations.RemoveIndex(
            model_name="productquestion",
            name="question_product_visible",
        ),
        migrations.RenameIndex(
            model_name="productquestion",
            new_name="question_product_store",
            old_name="question_store_visible",
        ),
        migrations.RenameIndex(
            model_name="productquestion",
            new_name="question_product_topic",
            old_name="question_topic_visible",
        ),
        migrations.RemoveField(
            model_name="productquestion",
            name="is_answered",
        ),
        migrations.AlterField(
            model_name="productanswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="topic",
            field=models.CharField(
                choices=[
                    ("general", "Genel"),
                    ("price", "Fiyat / İndirim"),
                    ("payment", "Ödeme"),
                    ("availability", "Stok / Bulunabilirlik"),
                    ("shipping", "Kargo / Teslimat"),
                    ("warranty", "Garanti / İade"),
                    ("gift", "Hediye Gönderimi"),
                    ("model_variant", "Model / Versiyon Farklılıkları"),
                    ("features", "Fonksiyon / Özellikler"),
                    ("content", "Ürün İçeriği"),
                    ("material", "Malzeme"),
                    ("color", "Renk Seçenekleri"),
                    ("size", "Boyut / Ölçü"),
                    ("weight", "Ağırlık"),
                    ("quantity", "Adet / Miktar"),
                    ("origin", "Menşei / Üretim Yeri"),
                    ("usage_area", "Kullanım Alanları"),
                    ("usage_instructions", "Kullanım Talimatları"),
                    ("installation", "Kurulum / Montaj"),
                    ("care", "Bakım / Temizlik"),
                    ("storage", "Saklama Koşulları"),
                    ("compatibility", "Uyumluluk"),
                    ("suitability", "Uygunluk"),
                    ("age", "Yaş Uygunluğu"),
                    ("safety", "Güvenlik"),
                    ("allergy", "Alerji / Hassasiyet"),
                    ("performance", "Performans"),
                    ("expiry", "Son Kullanma Tarihi"),
                    ("certification", "Sertifika / Standartlar"),
                ],
                default="general",
                max_length=30,
                verbose_name="Konu",
            ),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productanswer",
            index=models.Index(
                fields=["store", "is_visible", "created_at"],
                name="answer_store_visible",
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "is_visible", "-upvotes", "-created_at"],
                name="question_product_list",
            ),
        ),
        migrations.AddField(
            model_name="productquestionupvote",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvote_records",
                to="products.productquestion",
            ),
        ),
        migrations.AddField(
            model_name="productquestionupvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_question_upvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productquestionupvote",
            index=models.Index(
                fields=["user", "question"], name="upvote_user_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="productquestionupvote",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="unique_question_user_upvote"
            ),
        ),
    ]
