# Generated by Django 5.2.6 on 2026-09-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0020_productquestionupvote_alter_productquestion_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productanswer",
            name="is_read_by_user",
            field=models.BooleanField(default=False, verbose_name="Müşteri Okudu mu?"),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="variant_context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asked_questions",
                to="products.productvariant",
                verbose_name="Sorunun Sorulduğu Varyant",
            ),
        ),
    ]
