# Generated by Django 5.2.6 on 2026-09-02 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_productanswer_is_read_by_user_and_more"),
        ("store", "0003_alter_storeupdaterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productanswer",
            constraint=models.UniqueConstraint(
                fields=("question", "store"), name="answer_per_question"
            ),
        ),
    ]
